export const PRODUCTS = [
  {
    slug: "iphone-15-128gb",
    vsQuery: "Apple iPhone 15 128GB",
    amzQuery: "Apple iPhone 15 128GB smartphone",
    fkQuery: "Apple iPhone 15 128GB smartphone",
    category: "Smartphones",
    minPrice: 40000,
  },
  {
    slug: "iphone-14-128gb",
    vsQuery: "Apple iPhone 14 128GB",
    amzQuery: "Apple iPhone 14 128GB smartphone",
    fkQuery: "Apple iPhone 14 128GB smartphone",
    category: "Smartphones",
    minPrice: 30000,
  },
  {
    slug: "samsung-galaxy-s24",
    vsQuery: "Samsung Galaxy S24 256GB",
    amzQuery: "Samsung Galaxy S24 5G 256GB smartphone",
    fkQuery: "Samsung Galaxy S24 5G 256GB smartphone",
    category: "Smartphones",
    minPrice: 30000,
  },
  {
    slug: "oneplus-12",
    vsQuery: "OnePlus 12 256GB",
    amzQuery: "OnePlus 12 5G 256GB smartphone",
    fkQuery: "OnePlus 12 5G 256GB smartphone",
    category: "Smartphones",
    minPrice: 40000,
  },
  {
    slug: "redmi-note-13-pro",
    vsQuery: "Redmi Note 13 Pro 128GB",
    amzQuery: "Redmi Note 13 Pro 5G 128GB smartphone",
    fkQuery: "Redmi Note 13 Pro 5G 128GB smartphone",
    category: "Smartphones",
    minPrice: 15000,
  },
  {
    slug: "google-pixel-8",
    vsQuery: "Google Pixel 8 128GB",
    amzQuery: "Google Pixel 8 128GB smartphone",
    fkQuery: "Google Pixel 8 128GB smartphone",
    category: "Smartphones",
    minPrice: 30000,
  },
  {
    slug: "boat-rockerz-450",
    vsQuery: "boAt Rockerz 450",
    amzQuery: "boAt Rockerz 450 wireless headphone",
    fkQuery: "boAt Rockerz 450 wireless headphone",
    category: "Headphones",
    minPrice: 800,
  },
  {
    slug: "sony-wh-1000xm5",
    vsQuery: "Sony WH-1000XM5",
    amzQuery: "Sony WH-1000XM5 wireless headphone",
    fkQuery: "Sony WH-1000XM5 wireless headphone",
    category: "Headphones",
    minPrice: 15000,
  },
  {
    slug: "jbl-tune-760nc",
    vsQuery: "JBL Tune 760NC",
    amzQuery: "JBL Tune 760NC headphone",
    fkQuery: "JBL Tune 760NC headphone",
    category: "Headphones",
    minPrice: 2000,
  },
  {
    slug: "dell-inspiron-15",
    vsQuery: "Dell Inspiron 15 laptop",
    amzQuery: "Dell Inspiron 15 laptop Intel",
    fkQuery: "Dell Inspiron 15 laptop Intel",
    category: "Laptops",
    minPrice: 30000,
  },
  {
    slug: "hp-pavilion-15",
    vsQuery: "HP Pavilion 15 laptop",
    amzQuery: "HP Pavilion 15 laptop",
    fkQuery: "HP Pavilion 15 laptop",
    category: "Laptops",
    minPrice: 30000,
  },
  {
    slug: "samsung-55-4k-tv",
    vsQuery: "Samsung 55 inch 4K TV",
    amzQuery: "Samsung 55 inch 4K LED Smart TV",
    fkQuery: "Samsung 55 inch 4K LED Smart TV",
    category: "Televisions",
    minPrice: 25000,
  },
] as const;
