"use client";

import { useEffect, useState } from "react";
import { RefreshCw, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";

interface AIAnalysis {
  id: string;
  summary: string;
  recommendation: string;
  bestSource: string;
  confidenceNote?: string | null;
  generatedAt: string | Date;
}

const SOURCE_LABELS: Record<string, string> = {
  vijaysales: "Vijay Sales",
  amazon: "Amazon.in",
  flipkart: "Flipkart",
};

export function AIRecommendation({
  productId,
  cachedAnalysis,
}: {
  productId: string;
  cachedAnalysis?: AIAnalysis | null;
}) {
  const [analysis, setAnalysis] = useState<AIAnalysis | null>(cachedAnalysis ?? null);
  const [loading, setLoading] = useState(!cachedAnalysis);
  const [refreshing, setRefreshing] = useState(false);

  const fetch_ = async (force = false) => {
    force ? setRefreshing(true) : setLoading(true);
    try {
      const res = await fetch("/api/ai/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ productId }),
      });
      const { data } = await res.json();
      setAnalysis(data);
      if (force) toast.success("Analysis refreshed");
    } catch {
      toast.error("Failed to load analysis");
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    if (!cachedAnalysis) fetch_();
  }, [productId]); // eslint-disable-line react-hooks/exhaustive-deps

  if (loading) {
    return (
      <div className="space-y-2.5">
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-5/6" />
        <Skeleton className="h-4 w-4/6" />
      </div>
    );
  }

  if (!analysis) {
    return (
      <div className="text-center py-8">
        <p className="text-sm text-muted-foreground mb-3">No analysis yet</p>
        <Button size="sm" variant="outline" onClick={() => fetch_()}>
          Generate analysis
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
          <Sparkles className="h-3.5 w-3.5 text-primary" />
          Generated by LLaMA 3.3 (Groq)
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={() => fetch_(true)}
          disabled={refreshing}
          className="h-7 text-xs text-muted-foreground"
        >
          <RefreshCw className={`h-3 w-3 mr-1 ${refreshing ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      <div className="rounded-lg border border-border p-4 space-y-3 bg-muted/30">
        <div>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">
            Summary
          </p>
          <p className="text-sm leading-relaxed">{analysis.summary}</p>
        </div>
        <div className="border-t border-border pt-3">
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">
            Recommendation
          </p>
          <p className="text-sm leading-relaxed">{analysis.recommendation}</p>
        </div>
        {analysis.bestSource && (
          <div className="border-t border-border pt-3 flex items-center gap-2">
            <span className="text-xs text-muted-foreground">Best source:</span>
            <span className="text-xs font-medium bg-primary/10 text-primary px-2 py-0.5 rounded">
              {SOURCE_LABELS[analysis.bestSource] ?? analysis.bestSource}
            </span>
          </div>
        )}
        {analysis.confidenceNote && (
          <p className="text-xs text-muted-foreground border-t border-border pt-3">
            Note: {analysis.confidenceNote}
          </p>
        )}
      </div>

      <p className="text-xs text-muted-foreground">
        Generated {new Date(analysis.generatedAt).toLocaleDateString()}
      </p>
    </div>
  );
}
